# Generated by Django 4.0.3 on 2022-04-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
