# Generated by Django 4.0.3 on 2022-04-02 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_tasks_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progresstree',
            options={'ordering': ('id',)},
        ),
    ]
