# Generated by Django 4.0.3 on 2022-04-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_progresstree_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresstree',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
