# Generated by Django 4.0.3 on 2022-04-03 09:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_leaderboardentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeaderboardEntry',
            new_name='UserTree',
        ),
    ]
