# Generated by Django 4.0.3 on 2022-04-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_leaderboardentry_usertree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertree',
            name='tree',
        ),
        migrations.RemoveField(
            model_name='usertree',
            name='user',
        ),
        migrations.AddField(
            model_name='usertree',
            name='treelevel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usertree',
            name='username',
            field=models.CharField(default='changman', max_length=100),
        ),
    ]
